
package ch.admin.e_service.zefix._2015_06_26;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZefixService", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", wsdlLocation = "file:ZefixServiceProd.wsdl")
public class ZefixService
    extends Service
{

    private final static URL ZEFIXSERVICE_WSDL_LOCATION;
    private final static WebServiceException ZEFIXSERVICE_EXCEPTION;
    private final static QName ZEFIXSERVICE_QNAME = new QName("http://www.e-service.admin.ch/zefix/2015-06-26", "ZefixService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:ZefixServiceProd.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZEFIXSERVICE_WSDL_LOCATION = url;
        ZEFIXSERVICE_EXCEPTION = e;
    }

    public ZefixService() {
        super(__getWsdlLocation(), ZEFIXSERVICE_QNAME);
    }

    public ZefixService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZEFIXSERVICE_QNAME, features);
    }

    public ZefixService(URL wsdlLocation) {
        super(wsdlLocation, ZEFIXSERVICE_QNAME);
    }

    public ZefixService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZEFIXSERVICE_QNAME, features);
    }

    public ZefixService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZefixService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZefixServicePortType
     */
    @WebEndpoint(name = "ZefixServicePort")
    public ZefixServicePortType getZefixServicePort() {
        return super.getPort(new QName("http://www.e-service.admin.ch/zefix/2015-06-26", "ZefixServicePort"), ZefixServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZefixServicePortType
     */
    @WebEndpoint(name = "ZefixServicePort")
    public ZefixServicePortType getZefixServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.e-service.admin.ch/zefix/2015-06-26", "ZefixServicePort"), ZefixServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZEFIXSERVICE_EXCEPTION!= null) {
            throw ZEFIXSERVICE_EXCEPTION;
        }
        return ZEFIXSERVICE_WSDL_LOCATION;
    }

}
