
package ch.admin.e_service.zefix._2015_06_26;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZefixServicePortType", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ch.admin.e_service.zefix._2015_06_26.ObjectFactory.class,
    ch.ech.xmlns.ech_0010._4.ObjectFactory.class,
    ch.ech.xmlns.ech_0097._2.ObjectFactory.class
})
public interface ZefixServicePortType {


    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.ShabRefsByDateResponseType
     */
    @WebMethod(operationName = "GetSHABRefsByDate", action = "http://soap.zefix.admin.ch/GetSHABRefsByDate")
    @WebResult(name = "getSHABRefsByDateResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public ShabRefsByDateResponseType getSHABRefsByDate(
        @WebParam(name = "getSHABRefsByDateRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetSHABRefsByDateRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.ShabMessageResponseType
     */
    @WebMethod(operationName = "GetSHABMessage", action = "http://soap.zefix.admin.ch/GetSHABMessage")
    @WebResult(name = "getSHABMessageResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public ShabMessageResponseType getSHABMessage(
        @WebParam(name = "getSHABMessageRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetSHABMessageRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.LegalFormsResponseType
     */
    @WebMethod(operationName = "GetLegalForms", action = "http://soap.zefix.admin.ch/GetLegalForms")
    @WebResult(name = "getLegalFormsResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public LegalFormsResponseType getLegalForms(
        @WebParam(name = "getLegalFormsRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetLegalFormsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.BfsCommunitiesResponseType
     */
    @WebMethod(operationName = "GetBFSCommunities", action = "http://soap.zefix.admin.ch/GetBFSCommunities")
    @WebResult(name = "getBFSCommunitiesResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public BfsCommunitiesResponseType getBFSCommunities(
        @WebParam(name = "getBFSCommunitiesRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetBFSCommunitiesRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.RegistryOfficesResponseType
     */
    @WebMethod(operationName = "GetRegistryOffices", action = "http://soap.zefix.admin.ch/GetRegistryOffices")
    @WebResult(name = "getRegistryOfficesResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public RegistryOfficesResponseType getRegistryOffices(
        @WebParam(name = "getRegistryOfficesRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        RegistryOfficesRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.DetailledResponseType
     */
    @WebMethod(operationName = "GetByEHRAidDetailled", action = "http://soap.zefix.admin.ch/GetByEHRAidDetailled")
    @WebResult(name = "getByEHRAidDetailledResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public DetailledResponseType getByEHRAidDetailled(
        @WebParam(name = "getByEHRAidDetailledRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetByEHRAidRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.FullResponseType
     */
    @WebMethod(operationName = "GetByEHRAidFull", action = "http://soap.zefix.admin.ch/GetByEHRAidFull")
    @WebResult(name = "getByEHRAidFullResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public FullResponseType getByEHRAidFull(
        @WebParam(name = "getByEHRAidFullRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetByEHRAidRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.DetailledResponseType
     */
    @WebMethod(operationName = "GetByCHidDetailled", action = "http://soap.zefix.admin.ch/GetByCHidDetailled")
    @WebResult(name = "getByCHidDetailledResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public DetailledResponseType getByCHidDetailled(
        @WebParam(name = "getByCHidDetailledRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetByCHidRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.FullResponseType
     */
    @WebMethod(operationName = "GetByCHidFull", action = "http://soap.zefix.admin.ch/GetByCHidFull")
    @WebResult(name = "getByCHidFullResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public FullResponseType getByCHidFull(
        @WebParam(name = "getByCHidFullRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetByCHidRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.DetailledResponseType
     */
    @WebMethod(operationName = "GetByUidDetailled", action = "http://soap.zefix.admin.ch/GetByUidDetailled")
    @WebResult(name = "getByUidDetailledResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public DetailledResponseType getByUidDetailled(
        @WebParam(name = "getByUidDetailledRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetByUidRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.FullResponseType
     */
    @WebMethod(operationName = "GetByUidFull", action = "http://soap.zefix.admin.ch/GetByUidFull")
    @WebResult(name = "getByUidFullResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public FullResponseType getByUidFull(
        @WebParam(name = "getByUidFullRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        GetByUidRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.admin.e_service.zefix._2015_06_26.ShortResponse
     */
    @WebMethod(operationName = "SearchByName", action = "http://soap.zefix.admin.ch/SearchByName")
    @WebResult(name = "shortResponse", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
    public ShortResponse searchByName(
        @WebParam(name = "searchByNameRequest", targetNamespace = "http://www.e-service.admin.ch/zefix/2015-06-26", partName = "body")
        SearchByNameRequest body);

}
